// Helper: build an ISO date string N days in the past.
const daysAgo = (n) =>
  new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

export const mockLinks = [
  {
    id: "l1",
    url: "https://www.tiktok.com/@chef/video/1111111111",
    platform: "TikTok",
    title: "15-minute weeknight pasta",
    thumbnailUrl: null,
    category: "Cooking",
    tags: ["recipe", "quick"],
    createdAtUtc: daysAgo(1),
  },
  {
    id: "l2",
    url: "https://www.youtube.com/watch?v=2222222222",
    platform: "YouTube",
    title: "Building a deck in React — full walkthrough",
    thumbnailUrl: null,
    category: "Learning",
    tags: ["tutorial", "react"],
    createdAtUtc: daysAgo(3),
  },
  {
    id: "l3",
    url: "https://www.instagram.com/reel/3333333333/",
    platform: "Instagram",
    title: "Studio apartment tour, 400 sq ft",
    thumbnailUrl: null,
    category: "Home",
    tags: ["home"],
    createdAtUtc: daysAgo(6),
  },
  {
    id: "l4",
    url: "https://www.facebook.com/reel/4444444444",
    platform: "Facebook",
    title: "Neighborhood block party highlights",
    thumbnailUrl: null,
    category: "Home",
    tags: ["community"],
    createdAtUtc: daysAgo(9),
  },
  {
    id: "l5",
    url: "https://www.tiktok.com/@runner/video/5555555555",
    platform: "TikTok",
    title: "Couch to 5K, week one recap",
    thumbnailUrl: null,
    category: "Fitness",
    tags: ["fitness", "running"],
    createdAtUtc: daysAgo(12),
  },
  {
    id: "l6",
    url: "https://www.youtube.com/watch?v=6666666666",
    platform: "YouTube",
    title: "Ambient mix for deep work",
    thumbnailUrl: null,
    category: "Music",
    tags: ["music", "focus"],
    createdAtUtc: daysAgo(15),
  },
  {
    id: "l7",
    url: "https://www.instagram.com/reel/7777777777/",
    platform: "Instagram",
    title: "Three-day Lisbon itinerary",
    thumbnailUrl: null,
    category: "Travel",
    tags: ["travel"],
    createdAtUtc: daysAgo(20),
  },
  {
    id: "l8",
    url: "https://www.tiktok.com/@office/video/8888888888",
    platform: "TikTok",
    title: "Office small talk, ranked",
    thumbnailUrl: null,
    category: "Humor",
    tags: ["comedy"],
    createdAtUtc: daysAgo(24),
  },
  {
    id: "l9",
    url: "https://www.youtube.com/watch?v=9999999999",
    platform: "YouTube",
    title: "Sourdough starter, day by day",
    thumbnailUrl: null,
    category: "Cooking",
    tags: ["recipe", "baking"],
    createdAtUtc: daysAgo(40),
  },
  {
    id: "l10",
    url: "https://www.instagram.com/reel/1010101010/",
    platform: "Instagram",
    title: "Azure deployment in five minutes",
    thumbnailUrl: null,
    category: "Learning",
    tags: ["tutorial", "cloud"],
    createdAtUtc: daysAgo(55),
  },
];
